In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("predic_end.csv")

In [3]:
targe = data['0']
labels = data['1']

In [4]:
print(type(targe))

<class 'pandas.core.series.Series'>


In [5]:
targe = np.array(targe).reshape(-1, 1) 
labels =  np.array(labels).reshape(-1, 1) 

## MLPRegressor
多层感知机回归器。
MLPRegressor进行迭代训练，因为在每个时间步长都计算了损耗函数相对于模型参数的偏导数以更新参数。

它还可以在损失函数中添加正则项，缩小模型参数以防止过拟合。


In [6]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

In [7]:
import numpy as np

In [8]:
vec_data = np.array(targe).reshape(len(targe),1)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(vec_data, labels,random_state=1)

In [10]:
X_train, X_test, y_train, y_test

(array([[20170202225654],
        [20170202111526],
        [20170202131026],
        ...,
        [20170202202013],
        [20170202225911],
        [20170202140153]], dtype=int64),
 array([[20170202131135],
        [20170202123207],
        [20170202174609],
        ...,
        [20170202013910],
        [20170202124750],
        [20170202233808]], dtype=int64),
 array([[6],
        [2],
        [1],
        ...,
        [1],
        [6],
        [2]], dtype=int64),
 array([[2],
        [2],
        [6],
        ...,
        [8],
        [6],
        [1]], dtype=int64))

In [12]:
mlp = MLPRegressor(random_state=1, max_iter=500).fit(X_train,y_train)

C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


In [73]:
M = MLPRegressor(random_state=1, max_iter=500)

In [13]:
y_pred = mlp.predict(X_test)
print(y_pred)

[1 1 1 ... 1 1 1]


In [75]:
y_pred = np.array(y_pred)
# 四舍五入
y_pred = np.around(y_pred)
y_pred

array([-1.21172026e+10, -1.21172025e+10, -1.21172026e+10, ...,
       -1.21172025e+10, -1.21172025e+10, -1.21172026e+10])

In [76]:
mlp.score(X_test, y_test)

-2.5117914752833077e+19

In [84]:
from sklearn.model_selection import cross_val_score

In [43]:
scores = cross_val_score(M, targe, labels, cv=5)
scores

C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usi

array([-2.12652820e+06, -1.42505088e+05, -2.30353411e+17, -3.45611074e+16,
       -2.67985602e+17])

In [45]:
scores.mean()

-1.0658002400498821e+17

In [47]:
scores.std()

1.1770891146994826e+17

Extremely Randomized Trees

In [35]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier

In [57]:
clf_0 = DecisionTreeClassifier(max_depth=None, min_samples_split=2,
    random_state=0)
scores_decision = cross_val_score(clf_0, targe, labels, cv=5)
scores.mean()


clf_1 = RandomForestClassifier(n_estimators=10, max_depth=None,
    min_samples_split=2, random_state=0)
scores_random = cross_val_score(clf_1, targe, labels, cv=5)


clf_2 = ExtraTreesClassifier(n_estimators=10, max_depth=None,
    min_samples_split=2, random_state=0)
scores_Extra = cross_val_score(clf_2, targe, labels, cv=5)

C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example u

In [65]:
scores_decision
print(scores_decision)
print(scores_decision.mean())

[0.43253491 0.43253491 0.43253491 0.43253491 0.43255068]
0.43253806227480507


In [55]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor

In [40]:
rng = np.random.RandomState(1)
regr_1 = DecisionTreeRegressor(max_depth=4)
regr_2 = AdaBoostRegressor(DecisionTreeRegressor(max_depth=4),
                           n_estimators=300, random_state=rng)
regr_1.fit(X_train, y_train.ravel())
regr_2.fit(X_train, y_train.ravel())
y_1 = regr_1.predict(X_test)
y_2 = regr_2.predict(X_test)

In [32]:
y_1

array([3.81119602, 3.81119602, 3.81119602, ..., 3.81119602, 3.81119602,
       3.81119602])

In [43]:
y_2
print(np.round(y_2))

[4. 4. 4. ... 4. 4. 4.]


In [37]:
scores = cross_val_score(regr_1, targe, labels, cv=5)
scores

array([-1.65270664e-07, -4.04282594e-05, -2.37778496e-05, -4.41101863e-06,
       -1.66808255e-04])

In [38]:
scores = cross_val_score(regr_2, targe, labels, cv=5)
scores

C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usi

array([-1.80258312e-04, -3.57218036e-04, -2.79489375e-04, -2.67636087e-04,
       -7.66678642e-06])

绘制单独投票回归预测

In [57]:
reg1 = GradientBoostingRegressor(random_state=1)
reg2 = RandomForestRegressor(random_state=1)
reg3 = LinearRegression()

test_1 = reg1.fit(X_train, y_train.ravel())
test_2 = reg2.fit(X_train, y_train.ravel())
test_3 = reg3.fit(X_train, y_train.ravel())

ereg = VotingRegressor([('gb', reg1), ('rf', reg2), ('lr', reg3)])
test_4 = ereg.fit(X_train, y_train)

pred1 = reg1.predict(X_test)
pred2 = reg2.predict(X_test)
pred3 = reg3.predict(X_test)
pred4 = ereg.predict(X_test)

C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [58]:
pred1

array([3.81119602, 3.81119602, 3.81119602, ..., 3.81119602, 3.81119602,
       3.81119602])

In [59]:
scores = cross_val_score(test_1, targe, labels, cv=5)
scores

C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usi

array([-1.65270664e-07, -4.04282594e-05, -2.37778496e-05, -4.41101863e-06,
       -1.66808255e-04])

In [60]:
scores = cross_val_score(test_2, targe, labels, cv=5)
scores

C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:593: DataConversionWarning: A column-vector 

array([-3.33745720e-07, -3.88429747e-05, -2.26305481e-05, -3.09237781e-06,
       -1.79291753e-04])

In [61]:
scores = cross_val_score(test_3, targe, labels, cv=5)
scores

array([ 0.00037621,  0.00010569,  0.00047003,  0.00018196, -0.00019968])

In [62]:
scores = cross_val_score(test_4, targe, labels, cv=5)
scores

C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\HUAWEI\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usi

array([ 1.80582596e-04,  7.21412400e-05,  1.77867322e-04,  1.16219582e-04,
       -1.10546333e-04])